name: icon-register
main: org.iconrealms.register.IconRegisterPlugin
version: 1.0.0
api-version: "1.20"
author: IconRealms
commands:
  register:
    description: Register your IconRealms website account.
    usage: /register <email> <password>
    permission: iconregister.use
permissions:
  iconregister.use:
    default: true
